include:
  - project: 'city-of-helsinki/kuva/ci-cd-config/ci-configuration'
    ref: v2
    file: '/.gitlab-ci-template.yml'

variables:
  SERVICE_PORT: 4000

build-review:
  # These variables are available only for review env and are merged with the general variables defined above.
  extends: .build
  variables:
    DOCKER_IMAGE_NAME: '$CI_PROJECT_NAME-review'
    DOCKER_BUILD_ARG_GRAPHQL_PROXY_PORT: 4000
    DOCKER_BUILD_ARG_GRAPHQL_PROXY_CMS_API_BASE_URL: 'https://cms.test.kuva.hel.ninja/api/'
    DOCKER_BUILD_ARG_GRAPHQL_PROXY_API_BASE_URL: 'https://api.hel.fi'
    DOCKER_BUILD_ARG_GRAPHQL_PROXY_LINKED_EVENTS_API_BASE_PATH: '/linkedevents/v1/'
    DOCKER_BUILD_ARG_GRAPHQL_PROXY_LINKED_COURSES_API_BASE_PATH: '/linkedcourses/v1/'
    DOCKER_BUILD_ARG_GRAPHQL_PROXY_MAP_OPEN_DATA_API_BASE_URL: 'https://kartta.hel.fi/ws/geoserver/avoindata'
    DOCKER_BUILD_ARG_GRAPHQL_PROXY_SENTRY_DSN: '$GL_SENTRY_DSN'
    DOCKER_BUILD_ARG_GRAPHQL_PROXY_SENTRY_ENVIRONMENT: 'development'
  only:
    refs:
      - external_pull_requests

build-staging:
  extends: .build
  variables:
    DOCKER_IMAGE_NAME: '$CI_PROJECT_NAME-staging'
    DOCKER_BUILD_ARG_GRAPHQL_PROXY_PORT: 4000
    DOCKER_BUILD_ARG_GRAPHQL_PROXY_CMS_API_BASE_URL: 'https://cms.test.kuva.hel.ninja/api/'
    DOCKER_BUILD_ARG_GRAPHQL_PROXY_API_BASE_URL: 'https://api.hel.fi'
    DOCKER_BUILD_ARG_GRAPHQL_PROXY_LINKED_EVENTS_API_BASE_PATH: '/linkedevents-test/v1/'
    DOCKER_BUILD_ARG_GRAPHQL_PROXY_LINKED_COURSES_API_BASE_PATH: '/linkedcourses-test/v1/'
    DOCKER_BUILD_ARG_GRAPHQL_PROXY_MAP_OPEN_DATA_API_BASE_URL: 'https://kartta.hel.fi/ws/geoserver/avoindata'
    DOCKER_BUILD_ARG_GRAPHQL_PROXY_SENTRY_DSN: '$GL_SENTRY_DSN'
    DOCKER_BUILD_ARG_GRAPHQL_PROXY_SENTRY_ENVIRONMENT: 'staging'
  only:
    refs:
      - master

build-production:
  extends: .build
  variables:
    DOCKER_IMAGE_NAME: '$CI_PROJECT_NAME-production'
    DOCKER_BUILD_ARG_GRAPHQL_PROXY_PORT: 4000
    DOCKER_BUILD_ARG_GRAPHQL_PROXY_CMS_API_BASE_URL: 'https://cms.prod.kuva.hel.ninja/api/'
    DOCKER_BUILD_ARG_GRAPHQL_PROXY_API_BASE_URL: 'https://api.hel.fi'
    DOCKER_BUILD_ARG_GRAPHQL_PROXY_LINKED_EVENTS_API_BASE_PATH: '/linkedevents/v1/'
    DOCKER_BUILD_ARG_GRAPHQL_PROXY_LINKED_COURSES_API_BASE_PATH: '/linkedcourses/v1/'
    DOCKER_BUILD_ARG_GRAPHQL_PROXY_MAP_OPEN_DATA_API_BASE_URL: 'https://kartta.hel.fi/ws/geoserver/avoindata'
    DOCKER_BUILD_ARG_GRAPHQL_PROXY_SENTRY_DSN: '$GL_SENTRY_DSN'
    DOCKER_BUILD_ARG_GRAPHQL_PROXY_SENTRY_ENVIRONMENT: 'production'
  only:
    refs:
      - master
      - /^release-.*$/

review:
  variables:
    DOCKER_IMAGE_NAME: '$CI_PROJECT_NAME-review'
    POSTGRES_ENABLED: 0

staging:
  variables:
    DOCKER_IMAGE_NAME: '$CI_PROJECT_NAME-staging'
  only:
    refs:
      - master

production:
  variables:
    DOCKER_IMAGE_NAME: '$CI_PROJECT_NAME-production'
