export type CourseParams = {
  combinedText: string[];
  division: string[];
  end: string;
  endsAfter: string;
  endsBefore: string;
  inLanguage: string;
  include: string[];
  isFree: boolean;
  keywordAnd: string[];
  keywordNot: string[];
  keyword: string[];
  language: string;
  location: string[];
  page: number;
  pageSize: number;
  publisher: string;
  sort: string;
  start: string;
  startsAfter: string;
  startsBefore: string;
  superEvent: string;
  superEventType: string[];
  text: string;
  translation: string;
};
